// <auto-generated />
using BattleshipGame.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BattleshipGame.Data.Migrations
{
    [DbContext(typeof(BattleshipGameDbContext))]
    [Migration("20230809201026_seedingplayers")]
    partial class seedingplayers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("BattleshipGame.Data.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Gdynia Obluze",
                            Name = "karaokesound"
                        },
                        new
                        {
                            Id = 2,
                            City = "Gdynia Obluze",
                            Name = "nosia789"
                        },
                        new
                        {
                            Id = 3,
                            City = "Gdynia Pogorze",
                            Name = "pariparuva"
                        },
                        new
                        {
                            Id = 4,
                            City = "Gdynia Dzialki Lesne",
                            Name = "ostrorzne"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
