// <auto-generated />
using System;
using BattleshipGame.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BattleshipGame.Data.Migrations
{
    [DbContext(typeof(BattleshipGameDbContext))]
    [Migration("20230817212321_fieldandgamemodel-with-playerseeding")]
    partial class fieldandgamemodelwithplayerseeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("BattleshipGame.Data.Entities.FieldEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GameEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GameEntityId1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEmpty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHitted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Player")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ShipSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameEntityId");

                    b.HasIndex("GameEntityId1");

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("BattleshipGame.Data.Entities.GameEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Player1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Player2Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("BattleshipGame.Data.Entities.PlayerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "City1",
                            Name = "Player1"
                        },
                        new
                        {
                            Id = 2,
                            City = "City1",
                            Name = "Player2"
                        },
                        new
                        {
                            Id = 3,
                            City = "City1",
                            Name = "Player3"
                        },
                        new
                        {
                            Id = 4,
                            City = "City1",
                            Name = "Player4"
                        },
                        new
                        {
                            Id = 5,
                            City = "City1",
                            Name = "Player5"
                        });
                });

            modelBuilder.Entity("BattleshipGame.Data.Entities.FieldEntity", b =>
                {
                    b.HasOne("BattleshipGame.Data.Entities.GameEntity", null)
                        .WithMany("Player1Board")
                        .HasForeignKey("GameEntityId");

                    b.HasOne("BattleshipGame.Data.Entities.GameEntity", null)
                        .WithMany("Player2Board")
                        .HasForeignKey("GameEntityId1");
                });

            modelBuilder.Entity("BattleshipGame.Data.Entities.GameEntity", b =>
                {
                    b.HasOne("BattleshipGame.Data.Entities.PlayerEntity", "Player1")
                        .WithMany()
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BattleshipGame.Data.Entities.PlayerEntity", "Player2")
                        .WithMany()
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player1");

                    b.Navigation("Player2");
                });

            modelBuilder.Entity("BattleshipGame.Data.Entities.GameEntity", b =>
                {
                    b.Navigation("Player1Board");

                    b.Navigation("Player2Board");
                });
#pragma warning restore 612, 618
        }
    }
}
