// <auto-generated />
using BattleshipGame.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BattleshipGame.Data.Migrations
{
    [DbContext(typeof(BattleshipGameDbContext))]
    partial class BattleshipGameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("BattleshipGame.Data.Entities.FieldEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEmpty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHitted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShipSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("BattleshipGame.Data.Entities.GameEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Player1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Player2Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("BattleshipGame.Data.Entities.PlayerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanShoot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Game")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanShoot = true,
                            City = "City1",
                            Game = 0,
                            Name = "Player1"
                        },
                        new
                        {
                            Id = 2,
                            CanShoot = true,
                            City = "City1",
                            Game = 0,
                            Name = "Player2"
                        },
                        new
                        {
                            Id = 3,
                            CanShoot = true,
                            City = "City1",
                            Game = 0,
                            Name = "Player3"
                        },
                        new
                        {
                            Id = 4,
                            CanShoot = true,
                            City = "City1",
                            Game = 0,
                            Name = "Player4"
                        },
                        new
                        {
                            Id = 5,
                            CanShoot = true,
                            City = "City1",
                            Game = 0,
                            Name = "Player5"
                        });
                });

            modelBuilder.Entity("BattleshipGame.Data.Entities.FieldEntity", b =>
                {
                    b.HasOne("BattleshipGame.Data.Entities.PlayerEntity", "Player")
                        .WithMany("GameBoard")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BattleshipGame.Data.Entities.PlayerEntity", b =>
                {
                    b.Navigation("GameBoard");
                });
#pragma warning restore 612, 618
        }
    }
}
